### ISSUE TITLE
Request, add advanced scrcpy settings

### ISSUE THREAD

**Issue by Funtime60** [Frontesque/scrcpy-plus#49] opened 2024-02-29 20:43 UTC
There isn't an option to change the modifier key. Rather than ask for just that alone I thought I'd ask for a text box that allows for arbitrary scrcpy flags which would make coming over from pure scrpy easier.

**Comment by Frontesque** [comment] 2024-02-29 23:09
Duplicate of #8

**Closed by Frontesque** 2024-02-29 23:09 UTC
Labels: duplicate
